[package]
name = "data_template"
version = "0.1.0"
authors = ["Dell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
json = "0.12.4"
